### PR TITLE
Move to a precompiled parser

### PR DESCRIPTION
**Pull request by LamaAni**
# Feature/Behavior change

While working with pycron, I found that the parser itself is slow when converting/comparing a large array of datetime values.

I believe this is because the parser re-processes the cron string rather then generating a "precompiled" set of comparison methods. 

If this is of interest, I suggest converting the parser into a "pre-compilable" fashion where it will not need to recompile. I have done so for my project and would like to contribute this parser to the community. 

# Behavior
I have changed the parser structure to use classes, but the core functionally should remain the same. 

# Tests
All tests are passing, but I found that the behavior for:
```
"* * * * monday-sunday/3"
```
Seems to be incorrect. I would expect it to accept days, (monday, thursday and sunday) and
it dose not.

Thank you for your time

### CODE REVIEW

**Comment by kipe** [comment]
Hey, thanks for your work!

What interests me is when you say "slow when converting/comparing a large array of datetime values". What kind of usage are we talking about?

My initial feeling is that this kind of change goes a bit against what I originally wanted this library to be, and it was as the description says "Simple cron-like parser". These changes make the code itself fairly difficult to read and understand, but on the other hand the user-facing parts of the library don't change...

I'll have to think about this :D

**Comment by LamaAni** [comment]
> Hey, thanks for your work!
> 
> What interests me is when you say "slow when converting/comparing a large array of datetime values". What kind of usage are we talking about?
> 
> My initial feeling is that this kind of change goes a bit against what I originally wanted this library to be, and it was as the description says "Simple cron-like parser". These changes make the code itself fairly difficult to read and understand, but on the other hand the user-facing parts of the library don't change...
> 
> I'll have to think about this :D

Hi,

For your question about the speed:
For the cron string: `*/7 14-16 16-19 6,7,8 thu`
At 1M values (all results are true):
```shell
Completed regular in:            0:00:08.957663
Completed pre-built in:          0:00:01.357825
regular/pre-built: 6.597067368769908
```

To test with the current PR:
```python
check_date = datetime(2015, 6, 18, 16, 7)
check_count = 1000000
cron_string = "*/7 14-16 16-19 6,7,8 thu"

comparer = CronTimeComparer(cron_string)

for _ in range(0, check_count):
    comparer.is_in_range_or_equals(check_date)
```

**Comment by kipe** [comment]
I'm perhaps more interested in a real-life scenario where this would be used.

**Comment by LamaAni** [comment]
I am using the cron time-range configuration to process data. 

I have a simulation working on stock information (stock tick data), and I want to trade just between the days monday to friday, 10-4pm. For this type of configuration, the cron string is a very good format, that can be applied in production and easily tested in simulation. In this case, the is_now method is called many times (i.e. for each tick).

Since the cron time string format is well known, my implementation will remain consistent.

**Comment by LamaAni** [comment]
Hi, 
Any update on this?

**Comment by fritzwagner** [comment]
Hey, i am currently trying to write a program using the pycron module. 
Is there a way to schedule an action to run for example every 4th Friday ?
Thx for your work!

**Pull request closed without merging**
